#!/bin/bash
export files=`ls *.html`
echo "var tplObject = {" > /tmp/tpl.js
for file in $files
do
    echo `echo $file | cut -d'.' -f 1` :  >> /tmp/tpl.js
    echo "'" >> /tmp/tpl.js
    cat $file | sed "s/'/\\\\'/g" >> /tmp/tpl.js
    echo "'," >> /tmp/tpl.js
done
echo "};"  >> /tmp/tpl.js
uglifyjs /tmp/tpl.js > ../Scripts/tpl.min.js
